# Generated by Django 4.0.1 on 2022-10-11 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(None), related_name='Category_parent', to='home.category'),
        ),
    ]
