# Generated by Django 4.0.1 on 2022-10-11 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_category_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='sity',
            name='img',
            field=models.ImageField(null=True, upload_to='SityImage'),
        ),
    ]
