# Generated by Django 4.0.1 on 2022-10-16 13:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_company_user_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='autor',
            field=models.ForeignKey(null=True, on_delete=models.SET(None), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='phone',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
