# Generated by Django 4.0.1 on 2022-10-21 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_company_contact_phone_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
