# Generated by Django 4.0.1 on 2022-11-09 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_user_company_advertisement_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
