# Generated by Django 4.0.1 on 2022-11-10 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_advertisement_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
